//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ComplainDBContext : DbContext
    {
        public ComplainDBContext()
            : base("name=ComplainDBContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<csContactU> csContactUs { get; set; }
        public virtual DbSet<csContactUsAction> csContactUsActions { get; set; }
        public virtual DbSet<csContactUsStatus> csContactUsStatuses { get; set; }
        public virtual DbSet<csContactUsType> csContactUsTypes { get; set; }
    }
}
