//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class csContactU
    {
        public int ContactUsID { get; set; }
        public Nullable<int> AccountID { get; set; }
        public Nullable<int> ContactUsTypeID { get; set; }
        public Nullable<int> ContactUsStatusID { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Telephone { get; set; }
        public string Message { get; set; }
        public string LastAction { get; set; }
        public Nullable<bool> IsClosed { get; set; }
        public Nullable<System.DateTime> TransDate { get; set; }
        public string AWB { get; set; }
        public Nullable<int> SessionID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Ref { get; set; }
    }
}
